config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about' => 'static_pages#about'
  get '/help' => 'static_pages#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='')
    base_title = 'Social media'
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.google.com/", target="_blank">App</a>
    by <a href="http://www.twitter.com/", target="_blank">Chandra Sekhar</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path, target: "_blank" %></li>
      <li><%= link_to "Contact", '#', target: "_blank" %></li>
      <li><a href="http://www.fb.com/", target="_blank">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "caw", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="container">
  <div class="col-md-5 col-md-offset-4 col-sm-7 col-sm-offset-2">
    <h1>StaticPages#about</h1>
    <p>Find me in app/views/static_pages/about.html.erb</p>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<div class="container">
  <div class="col-md-5 col-md-offset-4 col-sm-7 col-sm-offset-2">
    <h1>StaticPages#help</h1>
    <p>Find me in app/views/static_pages/help.html.erb</p>
  </div>
</div>

<script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=46029464"></script>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="col-md-5 col-md-offset-2 col-sm-7 col-sm-offset-1">
    <%= image_tag("brba.jpg", size: '600x400', alt: 'Homepage Image', class: 'img img-rounded') %>
  </div>
</div>